gems:
  - jekyll-seo-tag

title: Quick Currency Converter

description: Online quick & easy multiple currency converter

author: RhaldKhein

url: https://rhaldkhein.github.io/qcc

logo: https://rhaldkhein.github.io/qcc/app/favicons/android-chrome-512x512.png

social:
  name: RhaldKhein
  links:
    - https://github.com/rhaldkhein